# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.1/configuration-reference
version: 2.1

jobs:
  gotest:
    docker:
      - image: golang:1.20
    working_directory: /terraform-provider-mysql
    steps:
      - checkout
      - run:
          name: Test
          environment:
            # DB override is there only to skip some tests.
            DB: mysql:something 
          command: |
            make test
      - run:
          name: Vet
          command: |
            make vet
  integration:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    parameters:
      target:
        type: string
    steps:
      - checkout
      - run:
          name: Install mysql client
          command: |
            sudo apt-get update
            sudo apt-get -f -y install mysql-client
      - run:
          name: Run test << parameters.target >>
          command: |
            make << parameters.target >>

workflows:
  all-tests:
    jobs:
      - integration:
          matrix:
            parameters:
              target: ["testversion5.6", "testversion5.7", "testversion8.0", "testpercona5.7", "testpercona8.0", "testmariadb10.3", "testmariadb10.8", "testmariadb10.10", "testtidb6.1.0"]
      - gotest
